### ISSUE TITLE
ImportError: libcublas.so.9.0: cannot open shared object file

### ISSUE THREAD

**Issue by Kevin-chen-sheng** [songlab-cal/tape-neurips2019#17]
ImportError: libcublas.so.9.0: cannot open shared object file

I have checked the tensorflow-gpu version.It is 1.13.2.Its cuda counterpart should be 10.
However, mine was 9, so I installed tensorflow version 1.12.0,
![image](https://user-images.githubusercontent.com/52196486/70893140-765e6d00-2025-11ea-9ecb-3f3fc9c3f1d5.png)

**Comment by rmrao** [comment]
This is an issue with tensorflow-gpu installation not with tape specifically, so not sure I can help.
