### ISSUE TITLE
how to debug in pycharm using this project

### ISSUE THREAD

**Issue by fishguysword** [songlab-cal/tape-neurips2019#18]
the old keras  project start in terminal,it is difficult to find the main file and due to the sacred control the logging and configure ,It is hard to using the dubug mode in pycharm?  any advice ? or using the pytorch version ?

**Comment by fishguysword** [comment]
dealed in the pytorch version!!

**Comment by rmrao** [comment]
Yup these types of issues are largely why we switched to pytorch and rewrote a lot of the configuration :smile:
