### ISSUE TITLE
Global Arguments question

### ISSUE THREAD

**Issue by spark157** [songlab-cal/tape-neurips2019#7]
In `@proteins.config `in `__main__.py` there are two default global arguments set as follows:

```
    freeze_embedding_weights = False  # noqa: F841
    save_outputs = False  # noqa: F841
```

Can you tell me what `freeze_embedding_weights` does?  If I want the pretrained unsupervised weights for the fluorescence task to remain fixed (ie. the embeddings will be constant) should I switch this to True?

For `save_outputs`, if this is False will outputs be saved? [See README.md|Saving Results - not sure if there is a discrepency here.] If 'save_outputs' is True what gets saved?

Thanks.

Scott

**Comment by thomas-a-neil** [comment]
Thanks for your questions!

`freeze_embedding_weights` does exactly as you describe - if you want to train the downstream task model without propagating gradient updates through the language model, you should set this flag to True

`save_outputs` will save the outputs of the validation pass into a file called `outputs.pkl`. When running `tape-eval`, outputs are automatically saved and this flag is ignored.
