### ISSUE TITLE
Citation for NetSurfP2.0

### ISSUE THREAD

**Issue by yangkky** [songlab-cal/tape-neurips2019#9]
Since the data for secondary structure was curated in this paper, should people cite them in addition to the PDB when using that dataset?

**Comment by rmrao** [comment]
Yes - as outlined in our [citation guidelines](https://github.com/songlab-cal/tape#citation-guidelines), anyone using a dataset from TAPE should cite both our paper and the group that generated or curated the dataset originally. We provide a [bibtex file](https://raw.githubusercontent.com/songlab-cal/tape/master/data_refs.bib) containing all relevant citations as well.

**Comment by nickbhat** [comment]
Yes this is a great catch. Went ahead and added it to master. Thanks!
